---
title: "Pawsey for USyd researchers"
output:
  html_document:
    toc: false
    toc_float: false

---

The [Pawsey Supercomputing Research Centre (Pawsey)](https://pawsey.org.au/) provides [high performance computing (HPC)](https://pawsey.org.au/systems/setonix/), [quantum computing](https://pawsey.org.au/quantum-computing-made-easy-pawseys-setonix-q-breaks-new-ground/), and [cutting edge visualisation platforms](https://pawsey.org.au/visualisation/) to Australian researchers. 


This guide has been developed to support University of Sydney researchers in setting up their computational workflows on Pawsey's [Setonix HPC](https://pawsey.org.au/systems/setonix/), with particular focus on key differences between Pawsey and other HPC facilities our researchers may be familiar with (for example, Artemis and Gadi HPCs).  

:::{.callout-note}
## Attention researchers
This guide is not an exhaustive resource for using Setonix. It is only intended to orient you to the system and provide direct topical links to key parts of the comprehensive documentation available from Pawsey.
:::

## Pawsey pages to bookmark 

- Pawsey [Using Supercomputers](https://pawsey.atlassian.net/wiki/spaces/US/pages/51929390/Using+Supercomputers) general HPC guide
    - This is a beginner friendly overview of using an HPC, including the basics of connection, text editing, job submission, file management, and more
- Pawsey [Setonix user guide](https://pawsey.atlassian.net/wiki/spaces/US/pages/51925434/Setonix+User+Guide)
    - Comprehensive technical information about working on Setonix
- Pawsey [User support](https://pawsey.org.au/support/) landing page
    - Quick links to documentation, help desk, and the Origin project management portal


## Alternatives to Pawsey

In addition to Pawsey, other research computing platforms are available to researchers at The University of Sydney. Please see our [Research Computing documentation](https://sydneyuni.atlassian.net/wiki/spaces/RC/overview?homepageId=173932782) for more information. 







