---
title: "Support and resources"
output:
  html_document:
    toc: false
    toc_float: false

---

:::{.callout-note}
## Attention researchers

Please see the [University of Sydney Research Computing documentation](https://sydneyuni.atlassian.net/wiki/spaces/RC/pages/3709928078/Get+support) for a comprehensive overview of support available to you as a University of Sydney researcher using Pawsey resources.
:::
</br>

## Technical documentation 

Familiarise yourself with Setonix using Pawsey's documentation and the University of Sydney's Research Computing documentation

* [Pawsey Setonix user guide](https://pawsey.atlassian.net/wiki/spaces/US/pages/51925434/Setonix+User+Guide)
* [USyd Research Computing HPC documentation](https://sydneyuni.atlassian.net/wiki/spaces/RC/pages/3710255449/National+tier-1+HPCs#Pawsey-Setonix) - more Pawsey content TBA

## Live and self-directed training

If you are new to HPC and/or Pawsey, we suggest you attend - TBA

There are various trainings offered by SIH and Pawsey on HPC and data analysis topics:

* [SIH training calendar](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/workshops-and-training/training-calendar.html)
* [Pawsey training calendar](https://opus.nci.org.au/display/Help/NCI+Training+and+Educational+Events)


## Demonstrations

HPC experts at SIH have created a series of videos to help you get jobs running on Pawsey:

TBA

## I need to talk to someone 

Please contact the following people depending on your needs:

TBA
